name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run test